### ISSUE TITLE
Error at script start

### ISSUE THREAD

**Issue by SirTerrific** [Fitus/Zaloha.sh#1] opened 2020-01-17 17:59 UTC
Hi,

I tried to use your script but I have this error

> ANALYZING /dlna/download/ AND /nas/dlna/

> ===========================================

>  Parsing ..............................................awk: /nas/dlna/.Zaloha_metadata/106_parser.awk: line 17: 

> runaway string constant "\", startP ...

> Zaloha.sh: Error on line 

> 1796

I'm on debian 10. 

I tried a sync local to local and local to nfs

Thanks for your help.

**Comment by Fitus** [comment] 2020-01-20 08:36
Hi,

thanks for reporting this issue. On your Ubuntu system, presumably, the awk command is mapped to mawk instead of GNU awk.

Mawk behaves differently in this particular case, being the root cause of the failure:

```bash
$ awk 'BEGIN {x="BSLASH"; gsub( /BSLASH/, "\"\\\\\"", x ); print x}'
"\\"
```

```bash
$ mawk 'BEGIN {x="BSLASH"; gsub( /BSLASH/, "\"\\\\\"", x ); print x}'
"\"
```

Could you please verify this assumption (i.e. awk = mawk, and awk exhibits the second behavior) ?

If so, the problem should be fixed by the latest commit named "Compatibility with MAWK".

Please download the newest version of Zaloha.sh and re-test.

If all is OK, I advice you to also use the --mawk option. This option tells Zaloha.sh to use mawk explicitly and also turns off mawk's i/o buffering while displaying progress of commands (where i/o buffering causes confusion and is unwanted). This is another mawk issue to be specially handled.

Let me know the outcome. Thanks

F.

**Comment by SirTerrific** [comment] 2020-01-20 20:51
With the command awk 'BEGIN {x="BSLASH"; gsub( /BSLASH/, "\"\\\\\"", x ); print x}' on my Debian buster I have the second result. Also I notice that mawk is install so I assume that awk is mapped to mawk.

Thanks for your help. 

I don't know if I should open another ticket but, how can I exclude some extensions files ? 

I tried --findSourceOps='-name nfo -prune -o' and  --findSourceOps='-name NFO -prune -o' but without success
or
--findSourceOps='-name *.nfo -prune -o' and  --findSourceOps='-name *.NFO -prune -o' but without success

**Closed as completed** 2020-01-20 22:05 UTC
